---
- hosts: localhost
  vars_files:
    - ./esx_vars.yml
  tasks:
    - name: Add a VMWare vSwitch with multiple NICs
      local_acton:
        module: vmware_vswitch
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        switch: sio_temp
        nics:
        - vmnic2
        - vmnic3
        mtu: 1500
        validate_certs: False
    - name: Add Management Network VM Portgroup
      local_acton:
        module: vmware_portgroup
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        switch_name: sio_temp
        portgroup_name: "sio_temp_pg{{item}}"
        with_items:
          - 1
          - 2
        vlan_id: 20
        validate_certs: False
    - name: Add VMK to ScaleIO Network
      local_action:
        module: vmware_vmkernel
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_user }}"
        password: "{{ esxi_pass }}"
        vswitch_name: sio_temp
        ip_address: "192.168.{{item}}.9"
        with_items:
          - 10
          - 11
        subnet_mask: "255.255.255.0"
        portgroup_name: "sio_temp_pg{{item}}"
        with_items:
          - 1
          - 2
        enable_mgmt: False
        enable_vsan: False
        enable_vmotion: False
        enable_ft: False
        vlan_id: 20
        mtu: 1500
        validate_certs: False
