---
- hosts: localhost
  vars_files:
    - ./esx_vars.yml
  tasks:
       - name: Create Datacenter
         local_action:
           module: vmware_datacenter
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           datacenter_name: "{{ vc_dc }}"
           state: present
           validate_certs: False
       - name: Create Cluster
         local_action:
           module: vmware_cluster
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           datacenter_name: "{{ vc_dc }}"
           cluster_name: "{{ vc_cl}}"
           enable_ha: yes
           enable_drs: yes
           enable_vsan: no
           state: present
           validate_certs: False
       - name: Create VM & MGMT Switches
         local_action:
           module: vmware_dvswitch
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           datacenter_name: "{{ vc_dc }}"
           switch_name: "{{ dvs_vm }}"
           mtu: 1500
           uplink_quantity: 2
           discovery_proto: cdp
           discovery_operation: listen
           state: present
           validate_certs: False
       - name: Create SIO Switches
         local_action:
           module: vmware_dvswitch
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           datacenter_name: "{{ vc_dc }}"
           switch_name: "{{ dvs_sio }}"
           mtu: 1500
           uplink_quantity: 2
           discovery_proto: cdp
           discovery_operation: listen
           state: present
           validate_certs: False
       - name: Add VM Portgroup to Switch
         local_action:
           module: vmware_dvs_portgroup
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           switch_name: "{{ dvs_vm }}"
           portgroup_name: "{{ vm_pg }}" 
           num_ports: 2
           portgroup_type: earlyBinding
           vlan_id: 344
           state: present
           validate_certs: False
       - name: Add MGMT Portgroup to Switch
         local_action:
           module: vmware_dvs_portgroup
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           switch_name: "{{ dvs_vm }}"
           portgroup_name: "{{ mgmt_pg }}" 
           num_ports: 2
           portgroup_type: earlyBinding
           vlan_id: 344
           state: present
           validate_certs: False
       - name: Add VLan 10 to Switch
         local_action:
           module: vmware_dvs_portgroup
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           switch_name: "{{ dvs_vm }}"
           portgroup_name: "{{ vl10_pg }}" 
           num_ports: 2
           portgroup_type: earlyBinding
           vlan_id: 10
           state: present
           validate_certs: False
       - name: Add VLan 345 to Switch
         local_action:
           module: vmware_dvs_portgroup
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           switch_name: "{{ dvs_vm }}"
           portgroup_name: "{{ vl345_pg }}" 
           num_ports: 2
           portgroup_type: earlyBinding
           vlan_id: 345
           state: present
           validate_certs: False
       - name: Add SIO Data1 to Switch
         local_action:
           module: vmware_dvs_portgroup
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           switch_name: "{{ dvs_sio }}"
           portgroup_name: "{{ sio1_pg }}" 
           num_ports: 2
           portgroup_type: earlyBinding
           vlan_id: 20
           state: present
           validate_certs: False
       - name: Add SIO Data2 to Switch
         local_action:
           module: vmware_dvs_portgroup
           hostname: "{{ vc_host }}"
           username: "{{ vc_user }}"
           password: "{{ vc_pass }}"
           switch_name: "{{ dvs_sio }}"
           portgroup_name: "{{ sio2_pg }}" 
           num_ports: 2
           portgroup_type: earlyBinding
           vlan_id: 20
           state: present
           validate_certs: False
